// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npacayzdpptuiklhnjvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wYWNheXpkcHB0dWlrbGhuanZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDE5NzcsImV4cCI6MjA3NDI3Nzk3N30.VtWPHPq6f4kkJbxHdl6MjEJ5QaF8eXNxb7MQILvBEmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});